var squareroot=Math.sqrt(441);
console.log(squareroot);
var firstname=("anjika");
var secondname=("ranjan");
var fullname=firstname.concat(secondname);
console.log(fullname);
var length=fullname.length;
console.log(length);
var sentence="She is playing";
var word=sentence.replace("She","He");
console.log(sentence);
console.log(word);
var sentence1=sentence.toUpperCase();
console.log(sentence1);
var sentence2=sentence1.toLowerCase();
console.log(sentence2);
var maxnumber=Math.max(1039,123);
console.log(maxnumber);
var minnumber=Math.min(109,202);
console.log(minnumber);
var pow=Math.pow(7,9);
console.log(pow);